name: stagex

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - "main"
    paths:
      - ".github/**"
      - "Cargo.lock"
      - "Cargo.toml"
      - "crates/**"
      - "Makefile"
      - "rust-toolchain.toml"
  pull_request:
    paths:
      - ".github/**"
      - "Cargo.lock"
      - "Cargo.toml"
      - "crates/**"
      - "images/**"
      - "Makefile"
      - "rust-toolchain.toml"
  workflow_dispatch: # Allows manual invocation

jobs:
  passport-verifier:
    name: Build passport-verifier image
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      id-token: write
      contents: read
      packages: write
    env:
      tags: >-
        ${{ github.ref == format('refs/heads/{0}', 'main') && 'latest' || '' }}
        ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) || '' }}
        ${{ github.event_name == 'push' && github.ref_name || '' }}
    strategy:
      matrix:
        target:
          - name: passport-verifier
    steps:
      - name: Checkout sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker setup
        uses: ./.github/actions/docker-setup
        with:
          dockerHub: ${{ secrets.DOCKERHUB_API_KEY }}
          ghcr: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ${{ matrix.target.name }}
        shell: bash
        run: |
          make -j$(nproc) out/${{ matrix.target.name }}/index.json

      - name: Load artifact to Docker
        run: |
          env -C out/${{ matrix.target.name }} tar -cf - . | docker load

      - name: Upload to GHCR
        run: |
          for tag in ${tags}; do
              docker tag "tkhq-tvc-passport-verifier/${{ matrix.target.name }}:latest" "ghcr.io/tkhq/${{ matrix.target.name }}:${tag}"
          done
          docker image push --all-tags "ghcr.io/tkhq/${{ matrix.target.name }}"
      - name: TVC deployment details
        run: |
          # Extract TVC deployment details from the built container image.
          first_tag=$(echo "${{ env.tags }}" | awk '{print $1}')
          container_url="ghcr.io/tkhq/${{ matrix.target.name }}:${first_tag}"
          container_digest=$(docker inspect --format='{{index .RepoDigests 0}}' "${container_url}" | cut -d '@' -f 2)
          docker create --name tmp-extract "${container_url}" /bin/true && docker cp tmp-extract:/tvc_app /tmp/binary && docker rm tmp-extract
          digest=$(sha256sum /tmp/binary | awk '{print $1}')
          echo ""
          echo "To deploy your application within TVC, use the following details:"
          echo ""
          echo "---- TVC Deployment Details ----"
          echo "Container Image URL: ${container_url}@${container_digest}"
          echo "Executable path: /tvc_app"
          echo "Expected Executable Digest: ${digest}"
          echo "--------------------------------"
          # Also use Github summary to display the details in a more visible way within build output
          echo "## TVC Deployment Details" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Container Image URL**: \`${container_url}@${container_digest}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Executable path**: \`/tvc_app\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Expected Executable Digest**: \`${digest}\`" >> $GITHUB_STEP_SUMMARY
